name: spark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]
  workflow_dispatch:

jobs:
  spark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.5.3'
        hadoop-version: '3'
    - run: spark-submit --version
    - name: Install dependencies
      run: pip install pandas openpyxl
    - name: Download dataset
      run: wget -O bank.xlsx ${{github.event.client_payload.dataseturl}}
    - name: Download bank.py
      run: wget -O bank.py ${{github.event.client_payload.codeurl}}
    - run: ls -la
    - run: spark-submit --master local bank.py
    - run: ls -la results
    - name: Commit and push results
      env: 
        CI_COMMIT_MESSAGE: "Update transaction analysis results"
        CI_COMMIT_AUTHOR: "SoyEtoor"
      run: |
        git config --global user.name "$CI_COMMIT_AUTHOR"
        git config --global user.email "tu_email@example.com"
        git add results/
        git commit -m "$CI_COMMIT_MESSAGE"
        git push
